// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: conf/v1/config_with_validate.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigWithValidate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server *ConfigWithValidate_Server `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data   *ConfigWithValidate_Data   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ConfigWithValidate) Reset() {
	*x = ConfigWithValidate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_v1_config_with_validate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigWithValidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigWithValidate) ProtoMessage() {}

func (x *ConfigWithValidate) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_config_with_validate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigWithValidate.ProtoReflect.Descriptor instead.
func (*ConfigWithValidate) Descriptor() ([]byte, []int) {
	return file_conf_v1_config_with_validate_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigWithValidate) GetServer() *ConfigWithValidate_Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ConfigWithValidate) GetData() *ConfigWithValidate_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ConfigWithValidate_Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Http *ConfigWithValidate_Server_Http `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc *ConfigWithValidate_Server_Grpc `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
}

func (x *ConfigWithValidate_Server) Reset() {
	*x = ConfigWithValidate_Server{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_v1_config_with_validate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigWithValidate_Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigWithValidate_Server) ProtoMessage() {}

func (x *ConfigWithValidate_Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_config_with_validate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigWithValidate_Server.ProtoReflect.Descriptor instead.
func (*ConfigWithValidate_Server) Descriptor() ([]byte, []int) {
	return file_conf_v1_config_with_validate_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ConfigWithValidate_Server) GetHttp() *ConfigWithValidate_Server_Http {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *ConfigWithValidate_Server) GetGrpc() *ConfigWithValidate_Server_Grpc {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type ConfigWithValidate_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Database *ConfigWithValidate_Data_Database `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis    *ConfigWithValidate_Data_Redis    `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
}

func (x *ConfigWithValidate_Data) Reset() {
	*x = ConfigWithValidate_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_v1_config_with_validate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigWithValidate_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigWithValidate_Data) ProtoMessage() {}

func (x *ConfigWithValidate_Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_config_with_validate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigWithValidate_Data.ProtoReflect.Descriptor instead.
func (*ConfigWithValidate_Data) Descriptor() ([]byte, []int) {
	return file_conf_v1_config_with_validate_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ConfigWithValidate_Data) GetDatabase() *ConfigWithValidate_Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *ConfigWithValidate_Data) GetRedis() *ConfigWithValidate_Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type ConfigWithValidate_Server_Http struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr    string               `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *ConfigWithValidate_Server_Http) Reset() {
	*x = ConfigWithValidate_Server_Http{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_v1_config_with_validate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigWithValidate_Server_Http) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigWithValidate_Server_Http) ProtoMessage() {}

func (x *ConfigWithValidate_Server_Http) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_config_with_validate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigWithValidate_Server_Http.ProtoReflect.Descriptor instead.
func (*ConfigWithValidate_Server_Http) Descriptor() ([]byte, []int) {
	return file_conf_v1_config_with_validate_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ConfigWithValidate_Server_Http) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ConfigWithValidate_Server_Http) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type ConfigWithValidate_Server_Grpc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr    string               `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *ConfigWithValidate_Server_Grpc) Reset() {
	*x = ConfigWithValidate_Server_Grpc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_v1_config_with_validate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigWithValidate_Server_Grpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigWithValidate_Server_Grpc) ProtoMessage() {}

func (x *ConfigWithValidate_Server_Grpc) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_config_with_validate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigWithValidate_Server_Grpc.ProtoReflect.Descriptor instead.
func (*ConfigWithValidate_Server_Grpc) Descriptor() ([]byte, []int) {
	return file_conf_v1_config_with_validate_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *ConfigWithValidate_Server_Grpc) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ConfigWithValidate_Server_Grpc) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type ConfigWithValidate_Data_Database struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Driver string `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *ConfigWithValidate_Data_Database) Reset() {
	*x = ConfigWithValidate_Data_Database{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_v1_config_with_validate_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigWithValidate_Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigWithValidate_Data_Database) ProtoMessage() {}

func (x *ConfigWithValidate_Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_config_with_validate_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigWithValidate_Data_Database.ProtoReflect.Descriptor instead.
func (*ConfigWithValidate_Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_v1_config_with_validate_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *ConfigWithValidate_Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *ConfigWithValidate_Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ConfigWithValidate_Data_Redis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network      string               `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr         string               `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout  *durationpb.Duration `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout *durationpb.Duration `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
}

func (x *ConfigWithValidate_Data_Redis) Reset() {
	*x = ConfigWithValidate_Data_Redis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_v1_config_with_validate_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigWithValidate_Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigWithValidate_Data_Redis) ProtoMessage() {}

func (x *ConfigWithValidate_Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_config_with_validate_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigWithValidate_Data_Redis.ProtoReflect.Descriptor instead.
func (*ConfigWithValidate_Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_v1_config_with_validate_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *ConfigWithValidate_Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ConfigWithValidate_Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ConfigWithValidate_Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *ConfigWithValidate_Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

var File_conf_v1_config_with_validate_proto protoreflect.FileDescriptor

var file_conf_v1_config_with_validate_proto_rawDesc = []byte{
	0x0a, 0x22, 0x63, 0x6f, 0x6e, 0x66, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62,
	0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdd, 0x06, 0x0a, 0x12, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x57, 0x69, 0x74, 0x68, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x42, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x57, 0x69, 0x74, 0x68, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x06, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x57, 0x69, 0x74, 0x68, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x1a, 0xc4, 0x02, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x43,
	0x0a, 0x04, 0x68, 0x74, 0x74, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x57, 0x69, 0x74,
	0x68, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x48, 0x74, 0x74, 0x70, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x04, 0x68,
	0x74, 0x74, 0x70, 0x12, 0x43, 0x0a, 0x04, 0x67, 0x72, 0x70, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x57, 0x69, 0x74, 0x68, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8,
	0x01, 0x01, 0x52, 0x04, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x57, 0x0a, 0x04, 0x48, 0x74, 0x74, 0x70,
	0x12, 0x1a, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06,
	0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x33, 0x0a, 0x07,
	0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x1a, 0x57, 0x0a, 0x04, 0x47, 0x72, 0x70, 0x63, 0x12, 0x1a, 0x0a, 0x04, 0x61, 0x64, 0x64,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52,
	0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x33, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x1a, 0xfd, 0x02, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x45, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x57, 0x69, 0x74, 0x68, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x05, 0x72, 0x65,
	0x64, 0x69, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x57, 0x69, 0x74, 0x68, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x64, 0x69,
	0x73, 0x52, 0x05, 0x72, 0x65, 0x64, 0x69, 0x73, 0x1a, 0x3a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x1a, 0xb3, 0x01, 0x0a, 0x05, 0x52, 0x65, 0x64, 0x69, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x3c, 0x0a, 0x0c,
	0x72, 0x65, 0x61, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x72,
	0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x3e, 0x0a, 0x0d, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x63, 0x6f,
	0x6e, 0x66, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_conf_v1_config_with_validate_proto_rawDescOnce sync.Once
	file_conf_v1_config_with_validate_proto_rawDescData = file_conf_v1_config_with_validate_proto_rawDesc
)

func file_conf_v1_config_with_validate_proto_rawDescGZIP() []byte {
	file_conf_v1_config_with_validate_proto_rawDescOnce.Do(func() {
		file_conf_v1_config_with_validate_proto_rawDescData = protoimpl.X.CompressGZIP(file_conf_v1_config_with_validate_proto_rawDescData)
	})
	return file_conf_v1_config_with_validate_proto_rawDescData
}

var file_conf_v1_config_with_validate_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_conf_v1_config_with_validate_proto_goTypes = []interface{}{
	(*ConfigWithValidate)(nil),               // 0: conf.v1.ConfigWithValidate
	(*ConfigWithValidate_Server)(nil),        // 1: conf.v1.ConfigWithValidate.Server
	(*ConfigWithValidate_Data)(nil),          // 2: conf.v1.ConfigWithValidate.Data
	(*ConfigWithValidate_Server_Http)(nil),   // 3: conf.v1.ConfigWithValidate.Server.Http
	(*ConfigWithValidate_Server_Grpc)(nil),   // 4: conf.v1.ConfigWithValidate.Server.Grpc
	(*ConfigWithValidate_Data_Database)(nil), // 5: conf.v1.ConfigWithValidate.Data.Database
	(*ConfigWithValidate_Data_Redis)(nil),    // 6: conf.v1.ConfigWithValidate.Data.Redis
	(*durationpb.Duration)(nil),              // 7: google.protobuf.Duration
}
var file_conf_v1_config_with_validate_proto_depIdxs = []int32{
	1,  // 0: conf.v1.ConfigWithValidate.server:type_name -> conf.v1.ConfigWithValidate.Server
	2,  // 1: conf.v1.ConfigWithValidate.data:type_name -> conf.v1.ConfigWithValidate.Data
	3,  // 2: conf.v1.ConfigWithValidate.Server.http:type_name -> conf.v1.ConfigWithValidate.Server.Http
	4,  // 3: conf.v1.ConfigWithValidate.Server.grpc:type_name -> conf.v1.ConfigWithValidate.Server.Grpc
	5,  // 4: conf.v1.ConfigWithValidate.Data.database:type_name -> conf.v1.ConfigWithValidate.Data.Database
	6,  // 5: conf.v1.ConfigWithValidate.Data.redis:type_name -> conf.v1.ConfigWithValidate.Data.Redis
	7,  // 6: conf.v1.ConfigWithValidate.Server.Http.timeout:type_name -> google.protobuf.Duration
	7,  // 7: conf.v1.ConfigWithValidate.Server.Grpc.timeout:type_name -> google.protobuf.Duration
	7,  // 8: conf.v1.ConfigWithValidate.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	7,  // 9: conf.v1.ConfigWithValidate.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_conf_v1_config_with_validate_proto_init() }
func file_conf_v1_config_with_validate_proto_init() {
	if File_conf_v1_config_with_validate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_conf_v1_config_with_validate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigWithValidate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conf_v1_config_with_validate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigWithValidate_Server); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conf_v1_config_with_validate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigWithValidate_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conf_v1_config_with_validate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigWithValidate_Server_Http); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conf_v1_config_with_validate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigWithValidate_Server_Grpc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conf_v1_config_with_validate_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigWithValidate_Data_Database); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conf_v1_config_with_validate_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigWithValidate_Data_Redis); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_conf_v1_config_with_validate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_v1_config_with_validate_proto_goTypes,
		DependencyIndexes: file_conf_v1_config_with_validate_proto_depIdxs,
		MessageInfos:      file_conf_v1_config_with_validate_proto_msgTypes,
	}.Build()
	File_conf_v1_config_with_validate_proto = out.File
	file_conf_v1_config_with_validate_proto_rawDesc = nil
	file_conf_v1_config_with_validate_proto_goTypes = nil
	file_conf_v1_config_with_validate_proto_depIdxs = nil
}
